# Generated by Django 4.2.6 on 2025-12-01 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_filename', models.CharField(max_length=255)),
                ('user_filename', models.CharField(max_length=255)),
                ('master_data', models.JSONField()),
                ('user_data', models.JSONField()),
                ('comparison_result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
